### ISSUE TITLE
[Feat] Apple App Privacy

### ISSUE THREAD

**Issue by 3Samourai** [FlineDev/FreemiumKit#2]
## Problem Statement

Apple requires a privacy disclosure for all new apps and app updates

## Suggested Solution

Since FreemiumKit is a component of the app, it would be great to create a page that outlines the data types used, similar to the [RevenueCat](https://www.revenuecat.com/docs/platform-resources/apple-platform-resources/apple-app-privacy) support page.

**Comment by Jeehut** [comment]
@3Samourai Thank you very much, that is a great suggestion. Just added a box into the privacy FAQ page to clarify:
https://freemiumkit.app/documentation/freemiumkit/faq-privacy

I also just [released SDK version 1.6.2](https://github.com/FlineDev/FreemiumKit/releases/tag/1.6.2) with a privacy manifest file so Xcode can automatically pick up the right labels when [generating a privacy report](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests#4239187) for your app.

Let me know if you have any other questions!

**Comment by 3Samourai** [comment]
Thanks :)
