### ISSUE TITLE
Paywall changes not updated after saving changes

### ISSUE THREAD

**Issue by GermanHernandez91** [FlineDev/FreemiumKit#4]
I have an issue where I made some changes to the header to variant A which is the only one I'm using. I saved the changes and upload it to remote but still I'm seeing my old paywall when testing the app either in local or using TestFlight.

**Comment by Jeehut** [comment]
@GermanHernandez91 I see you closed the ticket. Did it resolve itself? What exactly happened? Is there something I can improve? Or was it just a misunderstanding?

**Comment by GermanHernandez91** [comment]
Hey, thanks you for your reply.

I managed to fix it by dragging the asset again into the assets. For some reason I had an issue with that but it's all now working as expected.

Thanks !
