### ISSUE TITLE
[Bug] Redeem and Restore Button do not appear on iPhone SE sized phones on Paywall

### ISSUE THREAD

**Issue by ChristianSko** [FlineDev/FreemiumKit#5]
## Steps to Reproduce:
1. Have the paywall launch on an iPhone SE sized phone
2. Observe buttons at the bottom

## Expected Behavior:
`Restore` and `Redeem` buttons should appear and be tappable in some way.

## Current Behavior:
`Restore` and `Redeem` do not appear and are not tappable or discoverable in any way from what I could test.

## Environment
Production iPhone SE, iOS 18
![53D723C2-E2B8-427C-917C-51313C554D4D](https://github.com/user-attachments/assets/1028169f-3782-4d57-ad59-88b63841c7cc)

**Comment by Jeehut** [comment]
@ChristianSko I just updated the SDK in version `1.10.2` with a potential fix for this. Please take a look.

**Comment by ChristianSko** [comment]
@Jeehut Confirmed, it's working now. Thank you so much! 🚀
<img width="517" alt="image" src="https://github.com/user-attachments/assets/4cfcb327-c541-45a6-9396-d928dc33e397">

**Comment by Jeehut** [comment]
@ChristianSko You're welcome! Let me know if you run into any other issues.
