### ISSUE TITLE
Support checking for existing purchases on watchOS

### ISSUE THREAD

**Issue by emilismayilov095** [FlineDev/FreemiumKit#7]
The documentation says all apple platforms, but on WatchOS it gives build fail

**Comment by emilismayilov095** [comment]
![Uploading Снимок экрана 2024-12-01 в 17.38.18.png…]()

**Comment by Jeehut** [comment]
Thank you for bringing this up. I do understand your point and showing a paywall directly in your Apple Watch app might get supported in a later version. But when I look at the possible platforms I can add support for in Xcode, I don't see Apple Watch:
<img width="793" alt="Screenshot 2024-12-02 at 00 01 42" src="https://github.com/user-attachments/assets/713d6196-8e43-4d32-abba-a7c483fca4f6">

This is a sign that Apple had always designed Apple Watch apps as complements (formally "extensions") for iPhone apps. And this way, you can already use FreemiumKit for your Watch app today: Just sell your premium tier on the iPhone.

One point you might be right though is that it's currently not possible to check for the existence of a purchase on Apple Watch. And I think that's a good point that could also get fixed quite easily, without building a paywall UI for the Apple Watch. I will make sure to prioritize that aspect of Apple Watch support high and address it very soon.

I hope that this is what you were mainly aiming for. Let me know if you need something else.

**Comment by emilismayilov095** [comment]
@Jeehut, hi. Thanks for answear 

yes in SPM you indicated: platforms: [.iOS(.v15), .macOS(.v12), .tvOS(.v15), .visionOS(.v1)], I think you need add watchOS.

**Comment by Jeehut** [comment]
@emilismayilov095 It requires more than just adding the platform inside the platforms in the manifest. I need to exclude a bunch of view code and make sure everything still compiles. But I will give it a try now, if it's easy enough, you can expect watchOS support in the next SDK version. Let me see…

**Comment by Jeehut** [comment]
@emilismayilov095 It wasn't too hard, so I just released [version 1.16.0](https://github.com/FlineDev/FreemiumKit/releases/tag/1.16.0) of the SDK which adds Apple Watch support! 🚀 

Please let me know if you run into any problems.

**Comment by ChristianSko** [comment]
@Jeehut, I am testing this with my current app, which is focused on the Apple Watch.

So far, I have been sending a flag via WatchConnectivity. Using FreemiumKit.shared.hasPurchased would simplify things and reduce a considerable code amount on my end.

However, it is not working for me at the moment. I wondering if missed something on setup.

I have:
1. Added the FreemiumKit.config file in the project at the Apple Watch extension level and made sure its on that target.
2. On Watch Launch, I added `.environmentObject(FreemiumKit.shared).` to the parentView
3. On the screen with the premium features, I have `@EnvironmentObject var freemiumKit: FreemiumKit `set with `if freemiumKit.hasPurchased` in a view.

Is there any additional step I might be missing?

My expectation was that if a purchase is made on the phone, it would update immediately on the watch, however, it never updates for me.  Is my expectation correct or am I missing a step here?

**Comment by Jeehut** [comment]
@ChristianSko No, your expectation is what I would expect to happen as well. `FreemiumKit.shared` will automatically subscribe to StoreKit updates in your watch app. Assuming that when a user makes a purchase on the phone, the transaction arrives on the Watch as well, it should actually work. But maybe the updates work differently on watchOS.

I wonder what environment you tested this in. If you are using StoreKit testing in Xcode, maybe that doesn't properly communicate to watchOS in Debug mode? Or did you test in a separate environment?

Have you tested if after making a purchase and restarting the watchOS app, it picks up the purchase state? Maybe only live updates don't get passed on watchOS if purchased on another device, but subsequent starts work?

I have already in my roadmap that I have to test the watchOS details in more detail to figure these things out. My attempt was more like "let's assume everything works as documented" which seems not to work perfectly.

**Comment by ChristianSko** [comment]
Sorry @Jeehut, I completely missed your reply! Its been a while since I tested this, but I do have a branch with to test this. I'll try to come back with more specific information and ensure that it's not a user error on my end!

If there is anything else you want me to test, let me know so I can return with more tangible information!
