### ISSUE TITLE
[Bug] Purchases not showing in Freemiumkit App

### ISSUE THREAD

**Issue by ChristianSko** [FlineDev/FreemiumKit#9]
## Steps to Reproduce:
1. Make a purchase on a device via installation Xcode.
2. Check if the purchase appears in the Freemiumkit App.

## Expected Behavior:
1. The user receives a notification.
2. The purchase is displayed in the app.

## Current Behavior:
-  Purchases do not appear. Fetching returns the error below.
-  Modifying paywalls and saving to remote also return the same error below.
![6ACE4CF4-55CE-48A5-BDB3-9BDA88DA7E83_4_5005_c](https://github.com/user-attachments/assets/6e0631c2-41af-43d5-abab-f4777b40191e)

## Environment
- iOS 18.2
- Freemiumkit SDK 1.16.0
- Coincidentally, I recently added RevenueCat in observer mode to set up with TelemetryDeck. Not sure if there is any potential overlap, but I have removed it for testing, and it does not seem to make a difference. But raising in case its noteworthy.

## Notes  
-  I recently upgraded from FreemiumKit 1.12.0 to 1.16.0. I downgraded to test, but the same behavior persists.  
-  I believe it may have been working intermittently for a week, although that’s just a feeling.  
-  I discovered this issue because I noticed a purchase on App Store Connect that wasn't listed in FreemiumKit.

**Comment by Jeehut** [comment]
@ChristianSko Thank you for reporting. Investigating… 👀

**Comment by Jeehut** [comment]
@ChristianSko I could reproduce the issue on my end and fixed it. If you're curious: My cloud provider silently renamed my Redis database connection URL variable from `REDIS_TLS_URL` to `REDIS_URL`. 😔 Adjusted it in code and redeployed. That fixed the two reported buttons "Fetch latest" purchases and "Save Changes to remote" for me, so I'm positive it's also fixed for you. I'm not seeing any errors in my logs anymore.

Please let me know if you run into any other issues! The good news is that thanks to the way I designed the SDK, users making purchases should not be affected by this issue. You can learn more about it [here](https://freemiumkit.app/documentation/freemiumkit/faq-howitworks).

The bad news is that some purchases entries from the last few hours might not show up in your FreemiumKit app. But I'll tackle this afterwards by adding direct integration with the statistics reported to App Store Connect and syncing the live reported data with what's persisted on Apple's end, to fix any data holes. This will also make sure that reported data is always correct, including things like refunds. But that's a separate topic and out of scope for this issue. Expect that feature in a future update, it's on my roadmap!

Closing for now. Thank you again for the feedback! And sorry for the inconvenience. 🙏

**Comment by ChristianSko** [comment]
Thanks, @Jeehut

Yes indeed, I didn’t have any issues with the purchases, those still went through! 

I just updated the paywalls on my phone without any problems, so I think your fix worked! Thank you for addressing this so quickly 🚀  I'm always curious, so I appreciate the extra context , thanks again 🙏 😁
